// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tic-tac-toe.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type New struct {
	GameType             int64    `protobuf:"varint,1,opt,name=gameType,proto3" json:"gameType,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *New) Reset()         { *m = New{} }
func (m *New) String() string { return proto.CompactTextString(m) }
func (*New) ProtoMessage()    {}
func (*New) Descriptor() ([]byte, []int) {
	return fileDescriptor_tic_tac_toe_e3f9d7f670a323a2, []int{0}
}
func (m *New) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_New.Unmarshal(m, b)
}
func (m *New) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_New.Marshal(b, m, deterministic)
}
func (dst *New) XXX_Merge(src proto.Message) {
	xxx_messageInfo_New.Merge(dst, src)
}
func (m *New) XXX_Size() int {
	return xxx_messageInfo_New.Size(m)
}
func (m *New) XXX_DiscardUnknown() {
	xxx_messageInfo_New.DiscardUnknown(m)
}

var xxx_messageInfo_New proto.InternalMessageInfo

func (m *New) GetGameType() int64 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *New) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StateResult struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	State                []int64  `protobuf:"varint,2,rep,packed,name=state,proto3" json:"state,omitempty"`
	Result               int64    `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`
	LastMove             int64    `protobuf:"varint,4,opt,name=lastMove,proto3" json:"lastMove,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateResult) Reset()         { *m = StateResult{} }
func (m *StateResult) String() string { return proto.CompactTextString(m) }
func (*StateResult) ProtoMessage()    {}
func (*StateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_tic_tac_toe_e3f9d7f670a323a2, []int{1}
}
func (m *StateResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateResult.Unmarshal(m, b)
}
func (m *StateResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateResult.Marshal(b, m, deterministic)
}
func (dst *StateResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateResult.Merge(dst, src)
}
func (m *StateResult) XXX_Size() int {
	return xxx_messageInfo_StateResult.Size(m)
}
func (m *StateResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StateResult.DiscardUnknown(m)
}

var xxx_messageInfo_StateResult proto.InternalMessageInfo

func (m *StateResult) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StateResult) GetState() []int64 {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *StateResult) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *StateResult) GetLastMove() int64 {
	if m != nil {
		return m.LastMove
	}
	return 0
}

type Action struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Move                 int64    `protobuf:"varint,2,opt,name=move,proto3" json:"move,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_tic_tac_toe_e3f9d7f670a323a2, []int{2}
}
func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (dst *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(dst, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Action) GetMove() int64 {
	if m != nil {
		return m.Move
	}
	return 0
}

func init() {
	proto.RegisterType((*New)(nil), "proto.New")
	proto.RegisterType((*StateResult)(nil), "proto.StateResult")
	proto.RegisterType((*Action)(nil), "proto.Action")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TicTacToeClient is the client API for TicTacToe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TicTacToeClient interface {
	NewGame(ctx context.Context, in *New, opts ...grpc.CallOption) (*StateResult, error)
	Move(ctx context.Context, in *Action, opts ...grpc.CallOption) (*StateResult, error)
}

type ticTacToeClient struct {
	cc *grpc.ClientConn
}

func NewTicTacToeClient(cc *grpc.ClientConn) TicTacToeClient {
	return &ticTacToeClient{cc}
}

func (c *ticTacToeClient) NewGame(ctx context.Context, in *New, opts ...grpc.CallOption) (*StateResult, error) {
	out := new(StateResult)
	err := c.cc.Invoke(ctx, "/proto.TicTacToe/NewGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticTacToeClient) Move(ctx context.Context, in *Action, opts ...grpc.CallOption) (*StateResult, error) {
	out := new(StateResult)
	err := c.cc.Invoke(ctx, "/proto.TicTacToe/Move", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicTacToeServer is the server API for TicTacToe service.
type TicTacToeServer interface {
	NewGame(context.Context, *New) (*StateResult, error)
	Move(context.Context, *Action) (*StateResult, error)
}

func RegisterTicTacToeServer(s *grpc.Server, srv TicTacToeServer) {
	s.RegisterService(&_TicTacToe_serviceDesc, srv)
}

func _TicTacToe_NewGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(New)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicTacToeServer).NewGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TicTacToe/NewGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicTacToeServer).NewGame(ctx, req.(*New))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicTacToe_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Action)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicTacToeServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TicTacToe/Move",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicTacToeServer).Move(ctx, req.(*Action))
	}
	return interceptor(ctx, in, info, handler)
}

var _TicTacToe_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TicTacToe",
	HandlerType: (*TicTacToeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewGame",
			Handler:    _TicTacToe_NewGame_Handler,
		},
		{
			MethodName: "Move",
			Handler:    _TicTacToe_Move_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tic-tac-toe.proto",
}

func init() {
	proto.RegisterFile("proto/tic-tac-toe.proto", fileDescriptor_tic_tac_toe_e3f9d7f670a323a2)
}

var fileDescriptor_tic_tac_toe_e3f9d7f670a323a2 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xcd, 0x6e, 0x1a, 0xed, 0x88, 0x1e, 0x06, 0xd1, 0xa5, 0xa7, 0x90, 0x53, 0xa0, 0xb6,
	0x82, 0xe2, 0x0f, 0xf0, 0xe4, 0xc9, 0x1c, 0x62, 0xfe, 0xc0, 0xba, 0x1d, 0xca, 0x42, 0xd3, 0x2d,
	0xcd, 0x68, 0xf0, 0xdf, 0x4b, 0x66, 0x57, 0x11, 0xf4, 0xb4, 0xef, 0xbd, 0x79, 0xc3, 0xb7, 0x03,
	0x37, 0x87, 0x63, 0xe0, 0x70, 0xc7, 0xde, 0xad, 0xd8, 0xba, 0x15, 0x07, 0x5a, 0x4b, 0x82, 0x33,
	0x79, 0xaa, 0x47, 0xd0, 0x0d, 0x8d, 0xb8, 0x80, 0xb3, 0xad, 0xed, 0xa9, 0xfb, 0x3c, 0x90, 0xc9,
	0xca, 0xac, 0xd6, 0xed, 0x8f, 0x47, 0x84, 0x7c, 0x6f, 0x7b, 0x32, 0xaa, 0xcc, 0xea, 0x79, 0x2b,
	0xba, 0xda, 0xc2, 0xf9, 0x2b, 0x5b, 0xa6, 0x96, 0x86, 0xf7, 0x1d, 0xe3, 0x25, 0x28, 0xbf, 0x49,
	0x8b, 0xca, 0x6f, 0xf0, 0x0a, 0x66, 0xc3, 0x34, 0x36, 0xaa, 0xd4, 0xb5, 0x6e, 0xa3, 0xc1, 0x6b,
	0x28, 0x8e, 0xd2, 0x37, 0x5a, 0x9a, 0xc9, 0x4d, 0xf0, 0x9d, 0x1d, 0xf8, 0x25, 0x7c, 0x90, 0xc9,
	0x23, 0xfc, 0xdb, 0x57, 0xb7, 0x50, 0x3c, 0x39, 0xf6, 0x61, 0xff, 0x87, 0x81, 0x90, 0xf7, 0xd3,
	0x86, 0x92, 0x44, 0xf4, 0x3d, 0xc1, 0xbc, 0xf3, 0xae, 0xb3, 0xae, 0x0b, 0x84, 0x4b, 0x38, 0x6d,
	0x68, 0x7c, 0xb6, 0x3d, 0x21, 0xc4, 0xa3, 0xd7, 0x0d, 0x8d, 0x0b, 0x4c, 0xfa, 0xd7, 0xff, 0xab,
	0x13, 0x5c, 0x42, 0x3e, 0xf1, 0xf0, 0x22, 0x4d, 0x23, 0xf4, 0xff, 0xf2, 0x5b, 0x21, 0xe1, 0xc3,
	0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf1, 0xad, 0xae, 0xf4, 0x5d, 0x01, 0x00, 0x00,
}
